using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CameraController : MonoBehaviour
{
    public GameObject cam1, cam2;
    bool camChange = true;

    // Start is called before the first frame update
    void Start()
    {
        cam2.SetActive(false);
        cam1.SetActive(true);
    }

    // Update is called once per frame
    void Update()
    {
        if (Eammon.instance.foundDan)
        {
            if (Input.GetKeyDown(KeyCode.F))
            {
                camChange = !camChange;
            }
        }
        if (camChange)
        {
            cam1.SetActive(true);
            cam2.SetActive(false);
        }
        else
        {
            cam1.SetActive(false);
            cam2.SetActive(true);
        }
    }

}
